travis:
  secure:
    BINSTAR_TOKEN: hB9Y0tngP23on8uJHtX2aG1Sruue7TvLmaVMn+kFohScw7El5ST5BAqHb7kTtVgex5JENzlgB3+s6YHi6Wwjzq6ilPIag6HwDsHhB0sbR3leaiA3VegO8ZlVT3weRcywMHHuqxbfE9txOqw+dYSBQCLhnxIpL53/GvJk/RJLUMQ85hu5lqQztOHKzS5XXmIF8fANYUgpb0OATrpJeDQOxK2iVQF+1/RGGiH6ygMaluW06KsEI4cFaxGE69+xT0WZYxU2056/oh9xNeRBuctNfRDm7YK8Q5r/b0PRV59kT3yRydjadmRTCEHogBnmIaKHGqnGs4bw+EGTsYdcY/9+ePUOPBXpYfFdIFSOcNpnU8gdfSyUjAdmH6n0leLHCnBjD/T9ietEkNah9KD1QVtEPtjdbtVMjdYHhE7VQP3AfhrqDR8pJEXnvchqZK5KzpYqF1dsTzY/Mp82qHOZIyQbFlXmjmLY8xumBRQvpOPn4C6RFdDJ4EUVlxgsjBYZRe7GEyZc3kLT3JuJynqZcyjQNQnqlvwND1g5qLZn0SPNeuUqKFqtpvQy4SKuEd0jSey9tftrr+itwN0Z5TsSHqAN1Kn3RJbFU3XyYUTsiJV7EhSilqYOXnJLBrifTVn53i9FqsmFvVhZswWjYR5+mwBfNHPOaC1Wnyr9hbmjhP3uZ0s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
